### ISSUE TITLE
Pot posta o propunere pentru un proiect, pentru cei interesati?

### ISSUE THREAD

**Issue by mihaisavezi** [dserban/webdev2015fall#38]
@dserban - Voiam sa intreb daca este ok cu dvs. sa postez un anunt pentru propunere pentru un proiect? Nu este pentru mine, este pentru o persoana din spatiul in care lucrez ( TechHub).

**Comment by dserban** [comment]
@mihaisavezi Daca implica una dintre cele doua tehnologii pe care le-am studiat la WebDev, sigur ca da.

**Comment by mihaisavezi** [comment]
E pentru AngularJS, o sa fac issue nou si o sa-l inchid pe acesta. Multumesc.
